{
 "title": "Bootcamp 15",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "site",
    "label": "Select Site",
    "query": "oslo,hannover,nuremberg,marseille,houston,sao_paulo,kuala_lumpur,chicago,rotterdam,london"
   },
   {
    "name": "production_line",
    "label": "Production Line",
    "query": {
     "query": "assets{parentExternalIds=['${site}_production']}"
    }
   },
   {
    "name": "machine",
    "label": "Machine",
    "query": {
     "query": "assets{parentIds=[$production_line]}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Production Line", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average OEE",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='oee'},assetSubtreeIds=[{id=$production_line}]})",
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "label": "{{externalId}}",
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    }
   ]
  },
  {
   "title": "Average OEE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='oee'},assetSubtreeIds=[{id=$production_line}]})",
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "label": "Average OEE",
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='oee'},assetSubtreeIds=[{id=$production_line}]}",
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    }
   ]
  },
  {
   "title": "Average Availability",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='availability'},assetSubtreeIds=[{id=$production_line}]})",
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "label": "{{externalId}}",
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    }
   ]
  },
  {
   "title": "Average Availability",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 10 },
   "targets": [
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='availability'},assetSubtreeIds=[{id=$production_line}]})",
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "label": "Average Availability",
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='availability'},assetSubtreeIds=[{id=$production_line}]}",
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    }
   ]
  },
  {
   "title": "Average Performance",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='performance'},assetSubtreeIds=[{id=$production_line}]})",
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "label": "{{externalId}}",
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    }
   ]
  },
  {
   "title": "Average Performance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 19 },
   "targets": [
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='performance'},assetSubtreeIds=[{id=$production_line}]})",
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "label": "Average Performance",
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='performance'},assetSubtreeIds=[{id=$production_line}]}",
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    }
   ]
  },
  {
   "title": "Average Quality",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='quality'},assetSubtreeIds=[{id=$production_line}]})",
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "label": "{{externalId}}",
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    }
   ]
  },
  {
   "title": "Average Quality",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 28 },
   "targets": [
    {
     "aggregation": "none",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "avg(ts{metadata={type='quality'},assetSubtreeIds=[{id=$production_line}]})",
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "label": "Average Quality",
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "expr": "ts{metadata={type='quality'},assetSubtreeIds=[{id=$production_line}]}",
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Custom",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    }
   ]
  },
  {
   "title": "Equipment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "OEE",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregation": "none",
       "assetQuery": {
        "includeSubTimeseries": true,
        "includeSubtrees": false,
        "relationshipsQuery": {
         "dataSetIds": [],
         "depth": 1,
         "isActiveAtTime": false,
         "isTypeTimeseries": false,
         "labels": {
          "containsAny": []
         },
         "limit": 1000,
         "sourceExternalIds": []
        },
        "target": "",
        "withRelationships": false
       },
       "eventQuery": {
        "activeAtTimeRange": true,
        "advancedFilter": "",
        "aggregate": {
         "name": "uniqueValues",
         "properties": [],
         "withAggregate": false
        },
        "columns": [
         "externalId",
         "type",
         "subtype",
         "description",
         "startTime",
         "endTime"
        ],
        "expr": ""
       },
       "expr": "ts{metadata={type='oee'},assetSubtreeIds=[{id=$machine}]}",
       "extractionPipelinesQuery": {
        "columns": [
         "name",
         "status",
         "lastUpdatedTime",
         "lastFailure",
         "lastSeen",
         "lastSuccess",
         "schedule",
         "data set",
         "message"
        ],
        "getRuns": false,
        "limit": 1000,
        "selections": []
       },
       "flexibleDataModellingQuery": {
        "externalId": "",
        "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
        "tsKeys": []
       },
       "relationshipsQuery": {
        "dataSetIds": [],
        "depth": 1,
        "isActiveAtTime": false,
        "isTypeTimeseries": false,
        "labels": {
         "containsAny": []
        },
        "limit": 1000,
        "sourceExternalIds": []
       },
       "tab": "Custom",
       "templateQuery": {
        "dataPath": "oEE_MachinesQuery.items",
        "datapointsPath": "GoodQuantity.datapoints",
        "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
        "groupBy": "Facility"
       }
      }
     ]
    },
    {
     "title": "OEE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 38 },
     "targets": [
      {
       "aggregation": "none",
       "assetQuery": {
        "includeSubTimeseries": true,
        "includeSubtrees": false,
        "relationshipsQuery": {
         "dataSetIds": [],
         "depth": 1,
         "isActiveAtTime": false,
         "isTypeTimeseries": false,
         "labels": {
          "containsAny": []
         },
         "limit": 1000,
         "sourceExternalIds": []
        },
        "target": "",
        "withRelationships": false
       },
       "eventQuery": {
        "activeAtTimeRange": true,
        "advancedFilter": "",
        "aggregate": {
         "name": "uniqueValues",
         "properties": [],
         "withAggregate": false
        },
        "columns": [
         "externalId",
         "type",
         "subtype",
         "description",
         "startTime",
         "endTime"
        ],
        "expr": ""
       },
       "expr": "ts{metadata={type='oee'},assetSubtreeIds=[{id=$machine}]}",
       "extractionPipelinesQuery": {
        "columns": [
         "name",
         "status",
         "lastUpdatedTime",
         "lastFailure",
         "lastSeen",
         "lastSuccess",
         "schedule",
         "data set",
         "message"
        ],
        "getRuns": false,
        "limit": 1000,
        "selections": []
       },
       "flexibleDataModellingQuery": {
        "externalId": "",
        "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
        "tsKeys": []
       },
       "relationshipsQuery": {
        "dataSetIds": [],
        "depth": 1,
        "isActiveAtTime": false,
        "isTypeTimeseries": false,
        "labels": {
         "containsAny": []
        },
        "limit": 1000,
        "sourceExternalIds": []
       },
       "tab": "Custom",
       "templateQuery": {
        "dataPath": "oEE_MachinesQuery.items",
        "datapointsPath": "GoodQuantity.datapoints",
        "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
        "groupBy": "Facility"
       }
      }
     ]
    },
    {
     "title": "Avaialbility",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregation": "none",
       "assetQuery": {
        "includeSubTimeseries": true,
        "includeSubtrees": false,
        "relationshipsQuery": {
         "dataSetIds": [],
         "depth": 1,
         "isActiveAtTime": false,
         "isTypeTimeseries": false,
         "labels": {
          "containsAny": []
         },
         "limit": 1000,
         "sourceExternalIds": []
        },
        "target": "",
        "withRelationships": false
       },
       "eventQuery": {
        "activeAtTimeRange": true,
        "advancedFilter": "",
        "aggregate": {
         "name": "uniqueValues",
         "properties": [],
         "withAggregate": false
        },
        "columns": [
         "externalId",
         "type",
         "subtype",
         "description",
         "startTime",
         "endTime"
        ],
        "expr": ""
       },
       "expr": "ts{metadata={type='availability'},assetSubtreeIds=[{id=$machine}]}",
       "extractionPipelinesQuery": {
        "columns": [
         "name",
         "status",
         "lastUpdatedTime",
         "lastFailure",
         "lastSeen",
         "lastSuccess",
         "schedule",
         "data set",
         "message"
        ],
        "getRuns": false,
        "limit": 1000,
        "selections": []
       },
       "flexibleDataModellingQuery": {
        "externalId": "",
        "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
        "tsKeys": []
       },
       "relationshipsQuery": {
        "dataSetIds": [],
        "depth": 1,
        "isActiveAtTime": false,
        "isTypeTimeseries": false,
        "labels": {
         "containsAny": []
        },
        "limit": 1000,
        "sourceExternalIds": []
       },
       "tab": "Custom",
       "templateQuery": {
        "dataPath": "oEE_MachinesQuery.items",
        "datapointsPath": "GoodQuantity.datapoints",
        "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
        "groupBy": "Facility"
       }
      }
     ]
    },
    {
     "title": "Availability",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 46 },
     "targets": [
      {
       "aggregation": "none",
       "assetQuery": {
        "includeSubTimeseries": true,
        "includeSubtrees": false,
        "relationshipsQuery": {
         "dataSetIds": [],
         "depth": 1,
         "isActiveAtTime": false,
         "isTypeTimeseries": false,
         "labels": {
          "containsAny": []
         },
         "limit": 1000,
         "sourceExternalIds": []
        },
        "target": "",
        "withRelationships": false
       },
       "eventQuery": {
        "activeAtTimeRange": true,
        "advancedFilter": "",
        "aggregate": {
         "name": "uniqueValues",
         "properties": [],
         "withAggregate": false
        },
        "columns": [
         "externalId",
         "type",
         "subtype",
         "description",
         "startTime",
         "endTime"
        ],
        "expr": ""
       },
       "expr": "ts{metadata={type='availability'},assetSubtreeIds=[{id=$machine}]}",
       "extractionPipelinesQuery": {
        "columns": [
         "name",
         "status",
         "lastUpdatedTime",
         "lastFailure",
         "lastSeen",
         "lastSuccess",
         "schedule",
         "data set",
         "message"
        ],
        "getRuns": false,
        "limit": 1000,
        "selections": []
       },
       "flexibleDataModellingQuery": {
        "externalId": "",
        "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
        "tsKeys": []
       },
       "relationshipsQuery": {
        "dataSetIds": [],
        "depth": 1,
        "isActiveAtTime": false,
        "isTypeTimeseries": false,
        "labels": {
         "containsAny": []
        },
        "limit": 1000,
        "sourceExternalIds": []
       },
       "tab": "Custom",
       "templateQuery": {
        "dataPath": "oEE_MachinesQuery.items",
        "datapointsPath": "GoodQuantity.datapoints",
        "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
        "groupBy": "Facility"
       }
      }
     ]
    },
    {
     "title": "Performance",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregation": "none",
       "assetQuery": {
        "includeSubTimeseries": true,
        "includeSubtrees": false,
        "relationshipsQuery": {
         "dataSetIds": [],
         "depth": 1,
         "isActiveAtTime": false,
         "isTypeTimeseries": false,
         "labels": {
          "containsAny": []
         },
         "limit": 1000,
         "sourceExternalIds": []
        },
        "target": "",
        "withRelationships": false
       },
       "eventQuery": {
        "activeAtTimeRange": true,
        "advancedFilter": "",
        "aggregate": {
         "name": "uniqueValues",
         "properties": [],
         "withAggregate": false
        },
        "columns": [
         "externalId",
         "type",
         "subtype",
         "description",
         "startTime",
         "endTime"
        ],
        "expr": ""
       },
       "expr": "ts{metadata={type='performance'},assetSubtreeIds=[{id=$machine}]}",
       "extractionPipelinesQuery": {
        "columns": [
         "name",
         "status",
         "lastUpdatedTime",
         "lastFailure",
         "lastSeen",
         "lastSuccess",
         "schedule",
         "data set",
         "message"
        ],
        "getRuns": false,
        "limit": 1000,
        "selections": []
       },
       "flexibleDataModellingQuery": {
        "externalId": "",
        "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
        "tsKeys": []
       },
       "relationshipsQuery": {
        "dataSetIds": [],
        "depth": 1,
        "isActiveAtTime": false,
        "isTypeTimeseries": false,
        "labels": {
         "containsAny": []
        },
        "limit": 1000,
        "sourceExternalIds": []
       },
       "tab": "Custom",
       "templateQuery": {
        "dataPath": "oEE_MachinesQuery.items",
        "datapointsPath": "GoodQuantity.datapoints",
        "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
        "groupBy": "Facility"
       }
      }
     ]
    },
    {
     "title": "Performance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 54 },
     "targets": [
      {
       "aggregation": "none",
       "assetQuery": {
        "includeSubTimeseries": true,
        "includeSubtrees": false,
        "relationshipsQuery": {
         "dataSetIds": [],
         "depth": 1,
         "isActiveAtTime": false,
         "isTypeTimeseries": false,
         "labels": {
          "containsAny": []
         },
         "limit": 1000,
         "sourceExternalIds": []
        },
        "target": "",
        "withRelationships": false
       },
       "eventQuery": {
        "activeAtTimeRange": true,
        "advancedFilter": "",
        "aggregate": {
         "name": "uniqueValues",
         "properties": [],
         "withAggregate": false
        },
        "columns": [
         "externalId",
         "type",
         "subtype",
         "description",
         "startTime",
         "endTime"
        ],
        "expr": ""
       },
       "expr": "ts{metadata={type='performance'},assetSubtreeIds=[{id=$machine}]}",
       "extractionPipelinesQuery": {
        "columns": [
         "name",
         "status",
         "lastUpdatedTime",
         "lastFailure",
         "lastSeen",
         "lastSuccess",
         "schedule",
         "data set",
         "message"
        ],
        "getRuns": false,
        "limit": 1000,
        "selections": []
       },
       "flexibleDataModellingQuery": {
        "externalId": "",
        "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
        "tsKeys": []
       },
       "relationshipsQuery": {
        "dataSetIds": [],
        "depth": 1,
        "isActiveAtTime": false,
        "isTypeTimeseries": false,
        "labels": {
         "containsAny": []
        },
        "limit": 1000,
        "sourceExternalIds": []
       },
       "tab": "Custom",
       "templateQuery": {
        "dataPath": "oEE_MachinesQuery.items",
        "datapointsPath": "GoodQuantity.datapoints",
        "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
        "groupBy": "Facility"
       }
      }
     ]
    },
    {
     "title": "Quality",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregation": "none",
       "assetQuery": {
        "includeSubTimeseries": true,
        "includeSubtrees": false,
        "relationshipsQuery": {
         "dataSetIds": [],
         "depth": 1,
         "isActiveAtTime": false,
         "isTypeTimeseries": false,
         "labels": {
          "containsAny": []
         },
         "limit": 1000,
         "sourceExternalIds": []
        },
        "target": "",
        "withRelationships": false
       },
       "eventQuery": {
        "activeAtTimeRange": true,
        "advancedFilter": "",
        "aggregate": {
         "name": "uniqueValues",
         "properties": [],
         "withAggregate": false
        },
        "columns": [
         "externalId",
         "type",
         "subtype",
         "description",
         "startTime",
         "endTime"
        ],
        "expr": ""
       },
       "expr": "ts{metadata={type='quality'},assetSubtreeIds=[{id=$machine}]}",
       "extractionPipelinesQuery": {
        "columns": [
         "name",
         "status",
         "lastUpdatedTime",
         "lastFailure",
         "lastSeen",
         "lastSuccess",
         "schedule",
         "data set",
         "message"
        ],
        "getRuns": false,
        "limit": 1000,
        "selections": []
       },
       "flexibleDataModellingQuery": {
        "externalId": "",
        "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
        "tsKeys": []
       },
       "relationshipsQuery": {
        "dataSetIds": [],
        "depth": 1,
        "isActiveAtTime": false,
        "isTypeTimeseries": false,
        "labels": {
         "containsAny": []
        },
        "limit": 1000,
        "sourceExternalIds": []
       },
       "tab": "Custom",
       "templateQuery": {
        "dataPath": "oEE_MachinesQuery.items",
        "datapointsPath": "GoodQuantity.datapoints",
        "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
        "groupBy": "Facility"
       }
      }
     ]
    },
    {
     "title": "Quality",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 62 },
     "targets": [
      {
       "aggregation": "none",
       "assetQuery": {
        "includeSubTimeseries": true,
        "includeSubtrees": false,
        "relationshipsQuery": {
         "dataSetIds": [],
         "depth": 1,
         "isActiveAtTime": false,
         "isTypeTimeseries": false,
         "labels": {
          "containsAny": []
         },
         "limit": 1000,
         "sourceExternalIds": []
        },
        "target": "",
        "withRelationships": false
       },
       "eventQuery": {
        "activeAtTimeRange": true,
        "advancedFilter": "",
        "aggregate": {
         "name": "uniqueValues",
         "properties": [],
         "withAggregate": false
        },
        "columns": [
         "externalId",
         "type",
         "subtype",
         "description",
         "startTime",
         "endTime"
        ],
        "expr": ""
       },
       "expr": "ts{metadata={type='quality'},assetSubtreeIds=[{id=$machine}]}",
       "extractionPipelinesQuery": {
        "columns": [
         "name",
         "status",
         "lastUpdatedTime",
         "lastFailure",
         "lastSeen",
         "lastSuccess",
         "schedule",
         "data set",
         "message"
        ],
        "getRuns": false,
        "limit": 1000,
        "selections": []
       },
       "flexibleDataModellingQuery": {
        "externalId": "",
        "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
        "tsKeys": []
       },
       "relationshipsQuery": {
        "dataSetIds": [],
        "depth": 1,
        "isActiveAtTime": false,
        "isTypeTimeseries": false,
        "labels": {
         "containsAny": []
        },
        "limit": 1000,
        "sourceExternalIds": []
       },
       "tab": "Custom",
       "templateQuery": {
        "dataPath": "oEE_MachinesQuery.items",
        "datapointsPath": "GoodQuantity.datapoints",
        "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
        "groupBy": "Facility"
       }
      }
     ]
    }
   ]
  }
 ]
}