environment:
  name: prod
  project: cdf-bootcamp-15-prod
  type: prod
  selected:
  - modules/bootcamp/data_foundation
  - modules/bootcamp/ice_cream_api
  - modules/bootcamp/use_cases/oee

variables:
  modules:
    bootcamp:
      CDF_PROJECT: ${CDF_PROJECT}
      IDP_CLIENT_ID: ${IDP_CLIENT_ID}
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET}
      IDP_TENANT_ID: ${IDP_TENANT_ID}
      CDF_URL: https://${CDF_CLUSTER}.cognitedata.com
      IDP_SCOPES: https://${CDF_CLUSTER}.cognitedata.com/.default
      IDP_TOKEN_URL: ${IDP_TOKEN_URL}
      # Groups IDs
      data_developer_source_id: c3b6782d-57fb-4d03-81c2-c3afec8ad2c2
      data_pipeline_oee_source_id: 93502e36-8879-46f6-aebf-b00bbd5b81b5
      readwrite_source_id: 9a1c7da3-68fa-4747-9162-2d8e565d9179
      readonly_source_id: 9a1c7da3-68fa-4747-9162-2d8e565d9179
      icapi_extractors_source_id: 961b3346-85d5-4b3a-b38c-21a6317ed835
      # Client creds
      data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID}
      data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET}
      icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
      icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}
      icapi_ds_external_id: ds_icapi
      use_cases:
        oee:
          uc_oee_ds_external_id: ds_uc_oee
