environment:
  name: test
  project: cdf-bootcamp-15-test
  type: test
  selected:
  - modules/bootcamp/data_foundation
  - modules/bootcamp/ice_cream_api
  - modules/bootcamp/use_cases/oee

variables:
  modules:
    bootcamp:
      CDF_PROJECT: ${CDF_PROJECT}
      IDP_CLIENT_ID: ${IDP_CLIENT_ID}
      IDP_CLIENT_SECRET: ${IDP_CLIENT_SECRET}
      IDP_TENANT_ID: ${IDP_TENANT_ID}
      CDF_URL: https://${CDF_CLUSTER}.cognitedata.com
      IDP_SCOPES: https://${CDF_CLUSTER}.cognitedata.com/.default
      IDP_TOKEN_URL: ${IDP_TOKEN_URL}
      # Groups IDs
      data_developer_source_id: 108560c4-c7f7-4830-bd82-568f097b283b
      data_pipeline_oee_source_id: 24e641dd-0002-4f8d-b6e7-e58033dd4899
      readwrite_source_id: 2baf7749-9fc7-4cf1-b6bf-36bdbea4c399
      readonly_source_id: 2baf7749-9fc7-4cf1-b6bf-36bdbea4c399
      icapi_extractors_source_id: ee7a45aa-0cc5-4e28-ad31-85f6ad0358f0
      # Client creds
      data_pipeline_oee_client_id: ${DATA_PIPELINE_OEE_CLIENT_ID}
      data_pipeline_oee_client_secret: ${DATA_PIPELINE_OEE_CLIENT_SECRET}
      icapi_extractors_client_id: ${ICAPI_EXTRACTORS_CLIENT_ID}
      icapi_extractors_client_secret: ${ICAPI_EXTRACTORS_CLIENT_SECRET}
      icapi_ds_external_id: ds_icapi
      use_cases:
        oee:
          uc_oee_ds_external_id: ds_uc_oee
