name: Validate and deploy to prod project

on:
  push:
    paths:
      - "ice-cream-dataops/**"
    branches:
      - main

env:
    PYTHON_VERSION: "3.11"
    TOOLKIT_VERSION: "0.3.0b4"   

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Cognite toolkit
        run: |
          pip install "cognite-toolkit==${{ env.TOOLKIT_VERSION }}"

      - name: Build & deploy toolkit manifests
        env:
            CDF_CLUSTER: ${{ secrets.CDF_CLUSTER }}
            CDF_PROJECT: ${{ secrets.CDF_PROJECT }}
            IDP_CLIENT_ID: ${{ secrets.IDP_CLIENT_ID }}
            IDP_CLIENT_SECRET: ${{ secrets.IDP_CLIENT_SECRET }}
            IDP_SCOPES: ${{ secrets.IDP_SCOPES }}
            IDP_TENANT_ID: ${{ secrets.IDP_TENANT_ID }}
            IDP_TOKEN_URL: ${{ secrets.IDP_TOKEN_URL }}
            DATA_PIPELINE_OEE_CLIENT_ID: ${{ secrets.DATA_PIPELINE_OEE_CLIENT_ID }}
            DATA_PIPELINE_OEE_CLIENT_SECRET: ${{ secrets.DATA_PIPELINE_OEE_CLIENT_SECRET }}
            ICAPI_EXTRACTORS_CLIENT_ID: ${{ secrets.ICAPI_EXTRACTORS_CLIENT_ID }}
            ICAPI_EXTRACTORS_CLIENT_SECRET: ${{ secrets.ICAPI_EXTRACTORS_CLIENT_SECRET }}
        run: |
            cdf-tk build --verbose --env=prod \
            && cdf-tk deploy
